---
namespace: iamgini
name: wordpress
version: 1.0.0
readme: README.md
authors:
  - Gineesh Madapparambath <net.gini@gmail.com>
description: Ansible WordPress Utilities
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - wordpress
  - ansible
  - devops
  - cms
  - website

dependencies: {}
repository: https://github.com/iamgini/ansible-collection-wordpress
documentation: https://github.com/iamgini/ansible-collection-wordpress
homepage: https://github.com/iamgini/ansible-collection-wordpress
issues: https://github.com/iamgini/ansible-collection-wordpress

#build_ignore:
#- .gitignore
#- changelogs/.plugin-cache.yaml
