---
# tasks file for nginx_install
- block:
    - name: Include OS based install
      ansible.builtin.include_tasks:
        file: "nginx_{{ ansible_os_family | default('not_supported') }}.yaml"
  rescue:
    - name: Not supported version
      ansible.builtin.debug:
        msg: "Not supported OS"